### ISSUE TITLE
typescript compilation of downstream package fails

### ISSUE THREAD

**Issue by fogti** [sindresorhus/p-lazy#6]
```
../node_modules/p-lazy/index.d.ts:4:47 - error TS2689: Cannot extend an interface 'Promise'. Did you mean 'implements'?

4 export default class PLazy<ValueType> extends Promise<ValueType> {
                                                ~~~~~~~
```
sadly, I have no idea how to fix this.

**Comment by sindresorhus** [comment]
This package runs fine in the tests on TS 4.5, so this sounds like a spurious error. My guess would be that your project does not support ESM, but is still trying to import this package.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
